### ISSUE TITLE
Build and push Docker image in CI

### ISSUE THREAD

**Issue by agustinmista** [jaedle/mirror-to-gitea#11]
Hi! 

I noticed there's no CI action to build and push the Docker image to DockerHub. 

I can take care of it if you want 😄

**Comment by jaedle** [comment]
Hi @agustinmista,

thanks for your offer! 🙏 

I would really appreciate if you could work on that. I would provide the required docker hub actions.

I think using tags and a manual could be a solution.

Back in the days I have been using the docker hub auto build function, but now this is restricted as I only have a free account. So the image was never manually build + pushed, but the automation is gone.

**Comment by agustinmista** [comment]
I have been using an action [like this one](https://github.com/agustinmista/latex-lhs2tex-docker/blob/main/.github/workflows/docker.yml) for my own images. Seems to work fine.

In this case it would be a matter of triggering it only when a tag is pushed:

```
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'   # Push events to every tag including hierarchical tags like v1.0/beta
```

If you agree with this I can give it a try and open a PR soon.
