### ISSUE TITLE
[Feature] Mirror Issues

### ISSUE THREAD

**Issue by arunavo4** [jaedle/mirror-to-gitea#27]
Mirroring issues from Github will be a good option. I will see if I can make a PR for this.

**Comment by arunavo4** [comment]
In case anyone wants to quickly test it until it gets merged


**Docker Hub:** [arunavo4/mirror-to-gitea](https://hub.docker.com/r/arunavo4/mirror-to-gitea)

**Docker CLI:**
```bash
docker run -d \
  --name mirror-to-gitea \
  --restart unless-stopped \
  -e GITEA_STARRED_ORGANIZATION=starred \
  -e GITEA_TOKEN=<token> \
  -e GITEA_URL=<url> \
  -e GITHUB_TOKEN=<token> \
  -e GITHUB_USERNAME=<username> \
  -e MIRROR_ISSUES=true \
  -e MIRROR_ORGANIZATIONS=true \
  -e MIRROR_PRIVATE_REPOSITORIES=true \
  -e MIRROR_STARRED=true \
  -e PRESERVE_ORG_STRUCTURE=true \
  -e SKIP_STARRED_ISSUES=true \
  -e USE_SPECIFIC_USER=false \
  arunavo4/mirror-to-gitea:latest
```
**Docker Compose:**
```yaml
version: "3.8"

services:
  mirror-to-gitea:
    image: arunavo4/mirror-to-gitea:latest
    container_name: mirror-to-gitea
    restart: unless-stopped
    environment:
      - GITEA_STARRED_ORGANIZATION=starred
      - GITEA_TOKEN=<token>
      - GITEA_URL=<url>
      - GITHUB_TOKEN=<token>
      - GITHUB_USERNAME=<username>
      - MIRROR_ISSUES=true
      - MIRROR_ORGANIZATIONS=true
      - MIRROR_PRIVATE_REPOSITORIES=true
      - MIRROR_STARRED=true
      - PRESERVE_ORG_STRUCTURE=true
      - SKIP_STARRED_ISSUES=true
      - USE_SPECIFIC_USER=false
```
